# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Stocks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stocks
	pod 'Charts'

  target 'StocksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StocksUITests' do
    # Pods for testing
  end

end
